name: deploy

on:
  push:
    tags:
    - 'st3-*'
    - 'st4-*'
  workflow_dispatch:

jobs:

  documents:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/configure-pages@v6
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build hatch
        python -m pip install -r docs/src/requirements.txt
    - run: |
        python -m zensical build -f zensical.yml --clean
    - uses: actions/upload-pages-artifact@v5
      with:
        path: site
    - uses: actions/deploy-pages@v5